spring:
  application:
    name: mail-service
  config:
    import: "optional:configserver:http://localhost:8888"
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: transon9900@gmail.com
    password: ynzd tqlm wdxb frxo
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

client:
  baseUrl: http://localhost:3010








