spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:8888"
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: order-service
      port: 27017
      host: localhost



