server:
  port: 8084
  servlet:
    context-path: /api/v1/cart-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  #connect to database
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart-service
#      authentication-database: admin
#      username: admin
#      password: admin
#      database: cart-service
#      port: 27017
#      host: localhost

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days