server:
  port: 8085
  servlet:
    context-path: /api/v1/cart-service

spring:
  #kafka server url
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.type.mapping: event:com.sondev.mailservice.model.MailEvent
        spring.json.trusted.packages: "*"
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

