server:
  port: 8083


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#connect to database
spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: order-service
      port: 27017
      host: localhost