server:
  port: 8081


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#connect to database
spring:
  datasource:
    #    url: jdbc:mysql://mysql-springboot-container:3306/e-commerce-microservice
    url: jdbc:mysql://localhost:3306/e-commerce-microservice
    username: root
    password: Dfer2205me
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true